name: hspec-setup
version: '0.1.1.1'
synopsis: Add an hspec test-suite in one command
description: ! '@hspec-setup@ is a command-line tool for adding an hspec

  test-suite with minimal work. See the

  <https://github.com/yamadapc/haskell-hspec-setup GitHub README>

  for more information.'
category: Development
author: Pedro Tacla Yamada
maintainer: tacla.yamada@gmail.com
copyright: Copyright (c) 2015 Pedro Tacla Yamada
license: MIT
homepage: https://github.com/yamadapc/haskell-hspec-setup
git: git://github.com/yamadapc/haskell-hspec-setup
extra-source-files:
- README.md
tested-with: ghc >=7.10

dependencies:
- ansi-wl-pprint
- pretty >=1.1.2.0
- base >=4 && <5
- directory
- directory-tree
- filepath
- process >=1.2
- projectroot >=0.2

library:
  source-dirs: src
  exposed-modules:
  - Test.Hspec.Setup

executables:
  hspec-setup:
    main: Main.hs
    source-dirs: bin
    dependencies:
      hspec-setup

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - language-dockerfile
    - QuickCheck
    - base
    - hspec
